### ISSUE TITLE
Crash with ViaFabricPlus

### ISSUE THREAD

**Issue by Felix14-v2** [TheKodeToad/Numeral-Ping#5]
### Description
Minecraft crashes when opening multiplayer screen.

### To reproduce
- Install [Numeral Ping](https://modrinth.com/mod/numeral-ping)
- Install [ViaFabricPlus](https://modrinth.com/mod/viafabricplus)
- Install necessary libs
- Launch Minecraft
- Open multiplayer screen
- See the error

### Info
- Fabric Loader 0.14.21
- Fabric API 0.83.0/0.83.1
- Minecraft 1.20/1.20.1
- YACL 3.0.1
- Debug mods (StackDeobf, Better log4j)

### Logs
[latest.log](https://github.com/TheKodeToad/Numeral-Ping/files/11764918/latest.log)
[crash-2023-06-16_04.21.26-client.txt](https://github.com/TheKodeToad/Numeral-Ping/files/11764920/crash-2023-06-16_04.21.26-client.txt)

### Related
[ViaFabricPlus#134](https://github.com/ViaVersion/ViaFabricPlus/issues/134)

**Comment by TheKodeToad** [comment]
Thank you for reporting this! I found a compromise that will probably work. Hopefully I'll get around to releasing this! :P

**Comment by TheKodeToad** [comment]
![image](https://github.com/TheKodeToad/Numeral-Ping/assets/57493648/c5997f0e-f4d5-45b5-99cc-113ecbafa009)
Turns out I initially made a mistake, but it seems to work now!
There's just a bit of duplicate information, but if you're not using ViaFabric it'll hide the tooltip entirely.
