### ISSUE TITLE
Incompatible with Essential

### ISSUE THREAD

**Issue by Longie520** [TheKodeToad/Numeral-Ping#6]
The game crashes either when I enter the "Multiplayer menu", or when I leave a server that I have been playing on for a long time. I already reported this incompatibility to Essential, I figured that I should report it here, too.

I attached a crash report from earlier :D 

[crash-2023-06-19_17.22.41-client.txt](https://github.com/TheKodeToad/Numeral-Ping/files/11815365/crash-2023-06-19_17.22.41-client.txt)

**Comment by Felix14-v2** [comment]
I guess that essential is incompatible with mods, not the other way around.

**Comment by Longie520** [comment]
> I guess that essential is incompatible with mods, not the other way around.

I agree tbh- Essential has been crashing a lot on its own actually...

**Comment by TheKodeToad** [comment]
Try with https://github.com/TheKodeToad/Numeral-Ping/actions/runs/5812607878

**Comment by Longie520** [comment]
Seems that Essential has fixed this issue :o 
Yayayayayayyayayaayayayyaayayyy

**Comment by Longie520** [comment]
Ye, essential to be fixed with the current version of NP (doesn't crash my game with essential anymore).
